import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ua';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.mainWebsite': 'Main Website',
    'footer.rights': 'All rights reserved.',
    'hero.badge': 'We are hiring',
    'hero.title1': 'Shape the Future',
    'hero.title2': 'of',
    'hero.title3': 'iGaming',
    'hero.subtitle': 'Join a world-class team building the next generation of entertainment. We combine creativity, technology, and data to create unforgettable experiences.',
    'hero.cta': 'View Open Roles',
    'hero.connected': 'Connected Culture',
    'hero.connectedDesc': 'A flat structure where every voice matters and ideas flow freely.',
    'benefits.title': 'Why Playson?',
    'benefits.subtitle': 'We offer more than just a job. We offer a place to grow, innovate, and make an impact.',
    'benefits.remote': 'Remote-First',
    'benefits.remoteDesc': 'Work from anywhere in our supported regions with full home-office setup support.',
    'benefits.health': 'Premium Health',
    'benefits.healthDesc': 'Comprehensive medical insurance including dental and mental health coverage.',
    'benefits.growth': 'Growth Budget',
    'benefits.growthDesc': 'Annual allowance for courses, conferences, and professional development.',
    'benefits.culture': 'Vibrant Culture',
    'benefits.cultureDesc': 'Regular team building, offsites, and a flat hierarchy where ideas win.',
    'benefits.perks': 'Perks & Culture',
    'benefits.enjoy': 'Enjoy the benefits',
    'benefits.item.remote': 'Remote & hybrid work',
    'benefits.item.flex': 'Flexibility in your schedule',
    'benefits.item.courses': 'Development courses',
    'benefits.item.bonus': 'Bonus system',
    'benefits.item.medical': 'Full medical insurance',
    'benefits.item.gatherings': 'Corporate gatherings',
    'benefits.item.engineering': 'Strong engineering focus',
    'benefits.item.flat': 'Flat structure & idea sharing',
    'culture.badge': 'Our Culture',
    'culture.title1': 'Life at ',
    'culture.title2': 'Playson',
    'culture.subtitle': 'More than just code and games. We are a community of creators, thinkers, and friends.',
    'culture.card1.title': 'Team Offsites',
    'culture.card1.desc': 'Annual gatherings in amazing locations to bond, strategize, and celebrate our wins together.',
    'culture.card2.title': 'Continuous Learning',
    'culture.card2.desc': 'We sponsor your growth. From technical certifications to leadership workshops.',
    'culture.card3.title': 'Health & Wellness',
    'culture.card3.desc': 'Comprehensive support for your physical and mental well-being, because a healthy team is a happy team.',
    'culture.card4.title': 'Innovation Days',
    'culture.card4.desc': 'Dedicated time to step away from the roadmap and build wild, experimental ideas.',
    'culture.hubs': 'GLOBAL HUBS',
    'culture.impact': 'Global Impact',
    'culture.impactDesc': 'From our hubs in Malta, Ukraine, Slovakia, and the UK, we\'re building technology that powers entertainment worldwide.',
    'culture.engineering': 'Engineering First',
    'culture.playsoners': 'Playsoners Worldwide',
    'culture.joinFamily': 'Join the family',
    'culture.energy': 'High Energy',
    'culture.energyDesc': 'We work hard and celebrate harder.',
    'locations.title': 'Choose where to work',
    'locations.slovakia': 'Slovakia',
    'locations.malta': 'Malta',
    'locations.ukraine': 'Ukraine',
    'locations.remote': 'Remote',
    'locations.bratislava': 'Bratislava',
    'locations.sliema': 'Sliema',
    'locations.kyiv': 'Kyiv',
    'locations.fully': 'Fully',
    'eng.badge': 'Hiring Engineers & Product Leaders',
    'eng.title': 'xPlatform.',
    'eng.subtitle': 'We are building a high-load, distributed platform that handles millions of transactions daily. Join us to solve complex engineering challenges at scale.',
    'eng.cta': 'View Technical Roles',
    'eng.stats.uptime': '99.99%',
    'eng.stats.uptimeLabel': 'Uptime',
    'eng.stats.uptimeSub': 'High availability',
    'eng.stats.tx': '50M+',
    'eng.stats.txLabel': 'Daily Tx',
    'eng.stats.txSub': 'High throughput',
    'eng.stats.latency': '<50ms',
    'eng.stats.latencyLabel': 'Latency',
    'eng.stats.latencySub': 'Global edge network',
    'eng.stats.deploy': '100+',
    'eng.stats.deployLabel': 'Deploys/Week',
    'eng.stats.deploySub': 'CI/CD pipeline',
    'eng.stack.title': 'Our tech stack:',
    'eng.stack.subtitle': 'Built with modern technologies for performance and scale.',
    'eng.join.title': 'Join Playson Engineering',
    'eng.join.subtitle': 'We combine agility, ownership, and deep technical expertise to deliver products that millions of people enjoy daily.',
    'eng.join.roles': 'Open Technical Roles',
    'eng.join.search': 'Search by role, keyword or location...',
    'home.engHub.badge': 'Engineering Hub',
    'home.engHub.title1': 'Building the',
    'home.engHub.title2': 'Next Gen',
    'home.engHub.title3': 'Platform?',
    'home.engHub.desc': 'Join our specialized Engineering & Product teams. We have a dedicated portal for technical roles, architecture deep-dives, and our tech stack.',
    'home.engHub.open': 'open positions',
    'home.engHub.waiting': 'waiting for you',
    'home.engHub.cta': 'Visit Engineering Hub',
    'home.roles.title': 'Open Roles',
    'home.roles.search': 'Search by role, keyword or location...',
    'job.apply': 'Apply Now',
    'job.about': 'About Playson',
    'job.aboutDesc': 'Playson is a leading game developer supplying cutting-edge innovative content in over 17 regulated jurisdictions and beyond. We have a portfolio of over 85 omni-channel casino games, tested and certified for all major European regulated territories.',
    'job.back': 'Back to all roles',
    'job.hot': 'Hot',
    'job.remote': 'Remote',
    'job.showLess': 'Show Less',
    'job.showMore': 'Show {count} More',
    'job.noPositions': 'No other open positions found matching your criteria.',
    'job.clearFilters': 'Clear filters',
    'job.cantFind': 'Don’t see your role listed?',
    'job.cantFindDesc': 'Submit your information and we’ll reach out soon.',
    'job.sendCv': 'Submit',
    'partners.title': 'Partnering with like-minded people',
    'partners.desc': 'With more than 10 years of industry experience, we collaborate with iGaming Leaders for joint development, sharing entertainment and fun with everyone.',
    'licensed.title': 'Licensed & Certified',
    'licensed.desc': 'We operate in regulated markets worldwide, holding licenses and certifications from the industry\'s most respected authorities.',
    'eng.badge': 'Hiring Engineers & Product Leaders',
    'eng.title1': 'xPlatform.',
    'eng.title2': 'Built for Scale.',
    'eng.desc': 'Join the team building a highly adaptable solution that provides superior gaming and business experience through flexible API, powerful BI tools, and streamlined integration.',
    'eng.viewRoles': 'View Open Roles',
    'eng.aboutX': 'About xPlatform',
    'eng.techStack': 'Our Tech Stack',
    'eng.techDesc': 'We use modern, scalable technologies to build our platform.',
    'eng.openRoles': 'Engineering Roles',
    'eng.search': 'Search by role, keyword or location...',
    'eng.noRoles': 'No engineering roles found matching your criteria.',
    'job.notFound': 'Job not found',
    'job.notFoundDesc': 'The position you\'re looking for might have been filled or removed.',
    'job.backToAll': 'Back to all jobs',
    'job.weAreHiring': 'We are hiring',
    'job.share': 'Share',
    'job.copied': 'Copied!',
    'job.copyLink': 'Copy Link',
    'job.shareLinkedIn': 'Share on LinkedIn',
    'job.downloadCard': 'Download Card',
    'job.generating': 'Generating...',
    'job.similar': 'Similar Roles',
  },
  ua: {
    'nav.mainWebsite': 'Головний сайт',
    'footer.rights': 'Всі права захищені.',
    'hero.badge': 'Ми наймаємо',
    'hero.title1': 'Створюй майбутнє',
    'hero.title2': '',
    'hero.title3': 'iGaming',
    'hero.subtitle': 'Приєднуйтесь до команди світового рівня, що створює розваги нового покоління. Ми поєднуємо креативність, технології та дані для створення незабутніх вражень.',
    'hero.cta': 'Переглянути вакансії',
    'hero.connected': 'Культура зв\'язку',
    'hero.connectedDesc': 'Плоска структура, де кожен голос має значення, а ідеї вільно поширюються.',
    'benefits.title': 'Чому Playson?',
    'benefits.subtitle': 'Ми пропонуємо більше, ніж просто роботу. Ми пропонуємо місце для зростання, інновацій та впливу.',
    'benefits.remote': 'Віддалена робота',
    'benefits.remoteDesc': 'Працюйте з будь-якого місця в наших підтримуваних регіонах з повною підтримкою облаштування домашнього офісу.',
    'benefits.health': 'Преміум здоров\'я',
    'benefits.healthDesc': 'Комплексне медичне страхування, включаючи стоматологію та психологічну підтримку.',
    'benefits.growth': 'Бюджет на розвиток',
    'benefits.growthDesc': 'Щорічна допомога на курси, конференції та професійний розвиток.',
    'benefits.culture': 'Яскрава культура',
    'benefits.cultureDesc': 'Регулярні тімбілдінги, виїзні заходи та плоска ієрархія, де перемагають ідеї.',
    'benefits.perks': 'Переваги та Культура',
    'benefits.enjoy': 'Насолоджуйтесь перевагами',
    'benefits.item.remote': 'Віддалена та гібридна робота',
    'benefits.item.flex': 'Гнучкий графік',
    'benefits.item.courses': 'Курси розвитку',
    'benefits.item.bonus': 'Бонусна система',
    'benefits.item.medical': 'Повне медичне страхування',
    'benefits.item.gatherings': 'Корпоративні заходи',
    'benefits.item.engineering': 'Сильний інженерний фокус',
    'benefits.item.flat': 'Плоска структура та обмін ідеями',
    'culture.badge': 'Наша Культура',
    'culture.title1': 'Життя в ',
    'culture.title2': 'Playson',
    'culture.subtitle': 'Більше, ніж просто код та ігри. Ми — спільнота творців, мислителів та друзів.',
    'culture.card1.title': 'Командні виїзди',
    'culture.card1.desc': 'Щорічні зустрічі в дивовижних місцях, щоб згуртуватися, розробити стратегію та відсвяткувати наші перемоги разом.',
    'culture.card2.title': 'Безперервне навчання',
    'culture.card2.desc': 'Ми спонсоруємо ваше зростання. Від технічних сертифікацій до лідерських воркшопів.',
    'culture.card3.title': 'Здоров\'я та благополуччя',
    'culture.card3.desc': 'Комплексна підтримка вашого фізичного та психічного благополуччя, адже здорова команда — це щаслива команда.',
    'culture.card4.title': 'Дні інновацій',
    'culture.card4.desc': 'Виділений час, щоб відійти від дорожньої карти та створювати сміливі, експериментальні ідеї.',
    'culture.hubs': 'ГЛОБАЛЬНІ ХАБИ',
    'culture.impact': 'Глобальний вплив',
    'culture.impactDesc': 'З наших хабів на Мальті, в Україні, Словаччині та Великобританії ми створюємо технології, які забезпечують розваги по всьому світу.',
    'culture.engineering': 'Інженерія на першому місці',
    'culture.playsoners': 'Плейсонерів по всьому світу',
    'culture.joinFamily': 'Приєднуйтесь до сім\'ї',
    'culture.energy': 'Висока енергія',
    'culture.energyDesc': 'Ми наполегливо працюємо і ще краще святкуємо.',
    'locations.title': 'Оберіть місце роботи',
    'locations.slovakia': 'Словаччина',
    'locations.malta': 'Мальта',
    'locations.ukraine': 'Україна',
    'locations.remote': 'Віддалено',
    'locations.bratislava': 'Братислава',
    'locations.sliema': 'Сліма',
    'locations.kyiv': 'Київ',
    'locations.fully': 'Повністю',
    'eng.badge': 'Шукаємо інженерів та продакт-лідерів',
    'eng.title': 'xPlatform.',
    'eng.subtitle': 'Ми створюємо високонавантажену розподілену платформу, яка щодня обробляє мільйони транзакцій. Приєднуйтесь до нас для вирішення складних інженерних завдань у великих масштабах.',
    'eng.cta': 'Переглянути технічні вакансії',
    'eng.stats.uptime': '99.99%',
    'eng.stats.uptimeLabel': 'Аптайм',
    'eng.stats.uptimeSub': 'Висока доступність',
    'eng.stats.tx': '50M+',
    'eng.stats.txLabel': 'Транзакцій/день',
    'eng.stats.txSub': 'Висока пропускна здатність',
    'eng.stats.latency': '<50ms',
    'eng.stats.latencyLabel': 'Затримка',
    'eng.stats.latencySub': 'Глобальна мережа',
    'eng.stats.deploy': '100+',
    'eng.stats.deployLabel': 'Деплоїв/Тиждень',
    'eng.stats.deploySub': 'CI/CD пайплайн',
    'eng.stack.title': 'Наш тех стек:',
    'eng.stack.subtitle': 'Створено за допомогою сучасних технологій для продуктивності та масштабування.',
    'eng.join.title': 'Приєднуйтесь до Playson Engineering',
    'eng.join.subtitle': 'Ми поєднуємо гнучкість, відповідальність та глибоку технічну експертизу для створення продуктів, якими щодня насолоджуються мільйони людей.',
    'eng.join.roles': 'Відкриті технічні вакансії',
    'eng.join.search': 'Пошук за роллю, ключовим словом або локацією...',
    'home.engHub.badge': 'Інженерний Хаб',
    'home.engHub.title1': 'Створюєш платформу',
    'home.engHub.title2': 'нового покоління',
    'home.engHub.title3': '?',
    'home.engHub.desc': 'Приєднуйтесь до наших спеціалізованих інженерних та продуктових команд. У нас є окремий портал для технічних ролей, глибокого занурення в архітектуру та нашого тех стеку.',
    'home.engHub.open': 'відкритих позицій',
    'home.engHub.waiting': 'чекають на вас',
    'home.engHub.cta': 'Відвідати Інженерний Хаб',
    'home.roles.title': 'Відкриті вакансії',
    'home.roles.search': 'Пошук за роллю, ключовим словом або локацією...',
    'job.apply': 'Подати заявку',
    'job.about': 'Про Playson',
    'job.aboutDesc': 'Playson — провідний розробник ігор, що постачає передовий інноваційний контент у понад 17 регульованих юрисдикціях та за їх межами. Ми маємо портфоліо з понад 85 омніканальних ігор для казино, протестованих та сертифікованих для всіх основних європейських регульованих територій.',
    'job.back': 'Повернутися до всіх вакансій',
    'job.hot': 'Гаряча',
    'job.remote': 'Віддалено',
    'job.showLess': 'Показати менше',
    'job.showMore': 'Показати ще {count}',
    'job.noPositions': 'Не знайдено інших відкритих вакансій, що відповідають вашим критеріям.',
    'job.clearFilters': 'Очистити фільтри',
    'job.cantFind': 'Не бачите своєї ролі в списку?',
    'job.cantFindDesc': 'Надішліть свою інформацію, і ми незабаром зв\'яжемося з вами.',
    'job.sendCv': 'Надіслати',
    'partners.title': 'Партнерство з однодумцями',
    'partners.desc': 'Маючи понад 10 років досвіду в індустрії, ми співпрацюємо з лідерами iGaming для спільного розвитку, ділячись розвагами та веселощами з кожним.',
    'licensed.title': 'Ліцензовано та сертифіковано',
    'licensed.desc': 'Ми працюємо на регульованих ринках по всьому світу, маючи ліцензії та сертифікати від найповажніших органів індустрії.',
    'eng.badge': 'Шукаємо інженерів та лідерів продуктів',
    'eng.title1': 'xPlatform.',
    'eng.title2': 'Створено для масштабування.',
    'eng.desc': 'Приєднуйтесь до команди, яка створює гнучке рішення, що забезпечує чудовий ігровий та бізнес-досвід завдяки гнучкому API, потужним інструментам BI та спрощеній інтеграції.',
    'eng.viewRoles': 'Переглянути вакансії',
    'eng.aboutX': 'Про xPlatform',
    'eng.techStack': 'Наш технологічний стек',
    'eng.techDesc': 'Ми використовуємо сучасні технології, що масштабуються, для створення нашої платформи.',
    'eng.openRoles': 'Інженерні вакансії',
    'eng.search': 'Пошук за ролю, ключовим словом або локацією...',
    'eng.noRoles': 'Не знайдено інженерних вакансій, що відповідають вашим критеріям.',
    'job.notFound': 'Вакансію не знайдено',
    'job.notFoundDesc': 'Посада, яку ви шукаєте, можливо, вже зайнята або видалена.',
    'job.backToAll': 'Повернутися до всіх вакансій',
    'job.weAreHiring': 'Ми наймаємо',
    'job.share': 'Поділитися',
    'job.copied': 'Скопійовано!',
    'job.copyLink': 'Копіювати посилання',
    'job.shareLinkedIn': 'Поділитися в LinkedIn',
    'job.downloadCard': 'Завантажити картку',
    'job.generating': 'Генерація...',
    'job.similar': 'Схожі вакансії',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
